# Generated by Django 3.0.5 on 2020-04-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='invitation_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
