# Generated by Django 3.0.5 on 2020-04-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_customusermodel_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customusermodel_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmailConfirmationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_token', models.UUIDField()),
                ('expiration_at', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailconfirmationmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailconfirmationmodel_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailconfirmationmodel_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
