# Generated by Django 3.0.5 on 2020-04-21 20:57

import CustomUser.models.customUser
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_auto_20200419_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=CustomUser.models.customUser.user_directory_path),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='user_name',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
