# Generated by Django 3.0.5 on 2020-04-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_auto_20200421_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='block_timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
