# Generated by Django 3.0.5 on 2020-04-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0007_auto_20200425_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedinuser',
            old_name='user',
            new_name='logged_in_user',
        ),
    ]
